Feat: global zoom for all charts
openclimatefix/quartz-frontend pull request #456
Opened 2024-01-22 14:55 UTC by rachel-labri-tipton

# Pull Request

## Description

Current code for chart with zoom function that has access to all charts. 

Fixes #409 

## How Has This Been Tested?

Ran the code locally. 

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

2024-04-10 12:43 UTC, rachel-labri-tipton commented
hey @braddf, it looks like the zoom has deployed ok. I clicked around and everything seems to be working on the deployed branch.  would it be possible to have a look at it and let me know if you're good if it get's merged to `dev`?

It seems the quartz-frontend has failed to deploy, but will this impact merging these changes to `dev`?

2024-04-11 10:32 UTC, braddf requested changes

2024-04-11 10:32 UTC, braddf commented on apps/nowcasting-app/components/charts/remix-line.tsx
> +            deltaView ? `absolute top-5 right-16 mr-3 z-10` : `absolute top-5 right-4 z-10`
If you could separate out the shared classes from this ternary that would be great, putting them at the beginning and then using a template string for the conditional classes, keeps things neat and DRY

2024-04-11 10:32 UTC, braddf commented on apps/nowcasting-app/components/charts/remix-line.tsx
> +            console.log("click onclick clicked", e?.activeLabel, timeOfInterest);
Console

2024-04-11 10:32 UTC, braddf commented on apps/nowcasting-app/components/charts/remix-line.tsx
> +            console.log("click onmousedown clicked");
Console

2024-04-11 10:32 UTC, braddf commented on apps/nowcasting-app/components/icons/icons.tsx
> +export const CloseButtonIconForZoom: React.FC<IconProps> = ({ className }) => (
Don't think we're using this X icon now?

2024-04-11 13:08 UTC, rachel-labri-tipton commented
hey @braddf, thanks for the feedback. I made the requested changes.

2024-04-15 08:37 UTC, braddf approved these changes
LGTM!

2024-04-15 08:38 UTC, merged